---
title: "bohemiaR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bohemiaR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bohemiaR)
```

## Instalación

Puedes instalar el paquete directamente desde GitHub usando una función del paquete `devtools`:

``` r
# install.packages("devtools")
devtools::install_github("pauinsanchez/bohemiaR")

library(bohemiaR)
```

## Funciones

### `Dime_Max`

Esta función devuelve una frase aleatoria de Max Estrella, con indicación de la escena en la que aparece.

``` r
Dime_Max()
#> Max Estrella: ¡Señor Centurión, yo también chanelo el sermo vulgaris!
#> (Escena cuarta)
```

### `Dime_Latino`

Esta función devuelve una frase aleatoria de don Latino de Híspalis, con indicación de la escena en la que aparece.

``` r
Dime_Latino()
#> Don Latino: ¡La verdad es que tienes una fisonomía algo rara!
#> (Escena duodécima)
```
